"""Placeholder for Qiskit IR compilation.

This module is reserved for a future compiler that translates the
ScaLERQEC intermediate representation (IR) into Qiskit
``QuantumCircuit`` objects.  This would allow users to leverage the
Qiskit ecosystem (transpilation, hardware backends, visualization)
with circuits generated by :class:`~scalerqec.QEC.qeccircuit.StabCode`.

.. note:: Not yet implemented.
"""


class qiskitIRCompiler:
    """Compiler stub for converting ScaLERQEC IR to Qiskit circuits.

    Intended to accept IR instruction lists (as produced by
    :meth:`~scalerqec.QEC.qeccircuit.StabCode.construct_IR_standard_scheme`)
    and emit equivalent ``qiskit.QuantumCircuit`` objects.

    .. note:: Not yet implemented.
    """

    def __init__(self) -> None:
        pass

    def compile_IR_to_qiskit(self, IR: str):
        """Translate an IR string into a Qiskit ``QuantumCircuit``.

        .. note:: Not yet implemented.

        Args:
            IR: The intermediate representation as a multi-line string,
                using the ScaLERQEC IR format (``Prop``, ``Parity``,
                etc.).

        Returns:
            A Qiskit ``QuantumCircuit`` (once implemented).
        """
        pass
